### PR TITLE
Wrote a simple neural network to do the classification

### PR DESCRIPTION
**Pull request by zhu-yifang**

### CODE REVIEW

**Comment by BartMassey** [comment]
Why did you delete `top-5`?

**Comment by zhu-yifang** [comment]
I merged it to `main`

**Comment by BartMassey** [comment]
Still, don't do that in general. You may want to go back to it later. It's not hurting anything.

**Comment by zhu-yifang** [comment]
Gotcha.

Best,
Yifang
________________________________

**Pull request merged**
